### ISSUE TITLE
Move repo to Dracula org

### ISSUE THREAD

**Issue by zenorocha** [nesl247/fish-theme-dracula#1]
Hey @nesl247!

Just noticed this repo on GitHub search. Do you plan to move it to the official org?

**Comment by nesl247** [comment]
We had had a discussion at a previous time, and the decision was to not move it because shell's can have so many layouts. I'm happy to revisit that decision with you though.

**Comment by zenorocha** [comment]
Ohhh got it. I'm afraid we already made that mistake by having zsh there.

**Comment by nesl247** [comment]
The only thing is that this is not the standard robbyrussell theme that is used for zsh/bash, so I'm not sure if it really should be used as the official dracula theme. If we are going to have themes, we should probably stick to a standard layout, which this is not.

**Comment by zenorocha** [comment]
You're right, if we're going to have those themes we need a standard layout.

**Comment by nesl247** [comment]
Closing because this theme is not using the standard dracula layout.
